### ISSUE TITLE
Failed to map API.DLL functi!!!

### ISSUE THREAD

**Issue by bg1pc** [JvanKatwijk/qt-dab#138]
Failed to map API.DLL functi!!!

**Comment by JvanKatwijk** [comment]
Can you be slightly more specific? I understand that you are running a
windows version, but can you specify what you have done

**Comment by bg1pc** [comment]
win7

**Comment by JvanKatwijk** [comment]
Thanks, but that is not enough I am afraid. If you want me to be able to
address an issue then you should tell me the steps you have taken such that
I can try to reconstruct what happens and address the issue

**Comment by bg1pc** [comment]
w7下装好后，不能起动，显示无法映射API.DLL函数！
After W7 is installed, it can't start, display... API. DLL function cannot be mapped!

**Comment by bg1pc** [comment]
After downloading 4 files, install them in turn

**Comment by JvanKatwijk** [comment]
How does this help me understanding your problem?

**Comment by bg1pc** [comment]
![Uploading 20190908_225430.jpg…]()

**Comment by bg1pc** [comment]
![Uploading 20190908_225430.jpg…]()
![Uploading 20190908_225430.jpg…]()

**Comment by bg1pc** [comment]
ok???

**Comment by JvanKatwijk** [comment]
Please send the picture to my mailaddress.uploading pictures does not work

**Comment by JvanKatwijk** [comment]
I cannot read the pictures that you sent. Please try to send a picture using my regular email address.
