### ISSUE TITLE
epgdec.h directory missing from CMakeLists.txt?

### ISSUE THREAD

**Issue by Warblefly** [JvanKatwijk/qt-dab#165]
Hello,

Thank you for working on this software. The qt.pro system of building worked first time for me. However, when using the cmake build system, I had to insert an extra line in the includes, to pick up the epgdec.h header.

`       ./includes/backend/data/epg`

with best wishes,
John

**Comment by JvanKatwijk** [comment]
Thanks,
is fixed in coming update
