### ISSUE TITLE
dabMini version inconsistency

### ISSUE THREAD

**Issue by wkazubski** [JvanKatwijk/qt-dab#179]
As in qt-dab relesase 3.5.3, if dabMini is built with qmake the version is 2.0 but if it is built with cmake the version is 1.0.

**Comment by JvanKatwijk** [comment]
Good point, will be adapted

**Comment by andimik** [comment]
Seems that is was solved in https://github.com/JvanKatwijk/qt-dab/commit/7abc27f7bacb5a80912379c9ba51ec6f94a08a40#diff-e6a39f825af7c665052bdda46a7b3586 

Please close the issue.
