### ISSUE TITLE
Please add topics to the repository

### ISSUE THREAD

**Issue by mendel5** [JvanKatwijk/qt-dab#196]
It would be great if you could add the following Github topics to this repository:

- [https://github.com/topics/sdr](https://github.com/topics/sdr)
- [https://github.com/topics/rtl-sdr](https://github.com/topics/rtl-sdr)
- [https://github.com/topics/dab](https://github.com/topics/dab)
- [https://github.com/topics/dabplus](https://github.com/topics/dabplus)

Thanks!

**Comment by andimik** [comment]
What is the benefit?

The 2nd shows 219 hits. The majority has nothing to do with DAB.

**Comment by mendel5** [comment]
@JvanKatwijk Thanks for accepting my suggestion. I think you mistyped [https://github.com/topics/dabplus](https://github.com/topics/dabplus) to [https://github.com/topics/dabplus-](https://github.com/topics/dabplus-)?

**Comment by mendel5** [comment]
Thanks for fixing it!
