### ISSUE TITLE
SNR shows wrong

### ISSUE THREAD

**Issue by DG9BFC** [JvanKatwijk/qt-dab#197]
hello jan
version 3.6 shows an snr of 24 db on a local station but it shows way lower on 3.7 (a few db only ?!?)

**Comment by andimik** [comment]
The same issue has been discussed in (closed) https://github.com/JvanKatwijk/qt-dab/issues/195

Jan fixed it already.

**Comment by DG9BFC** [comment]
???????

**Comment by andimik** [comment]
> Wrt the SNR: in one of the earlier versions a factor 2 was missing, that was fixed some time ago

I checked it, this was done on 7th December 2021 in 07f5b10da

radio.cpp#1698
dab-processor.cpp#332

**Comment by DG9BFC** [comment]
... factor 20 is higher so snr shoud show higher ... not??
but in 3.6 a local is shown with 24 and in 3.7 with 12 db .... maybe that factor 10 slipped back in when compiling the windows installer??

**Comment by DG9BFC** [comment]
ok ok ok problem solved ... somehow i have got a 3.7 that showed snr wrong ...
now downloaded it again ... installed again ... and snr is correct ... grmbl grmbl ... sorry for wasting your time
back in my hole
dg9bfc sigi
