### ISSUE TITLE
SNR compression shows zig zag line with odd settings in config

### ISSUE THREAD

**Issue by DG9BFC** [JvanKatwijk/qt-dab#221]
when i set even numbers in config for snr compression all seems fine .. when i set odd numbers (1,3,5 etc) it shows a zigzag line
![snr_view_odd](https://user-images.githubusercontent.com/17382592/121578969-8c3acb80-ca2b-11eb-8add-bbc026b58cf8.jpg)
....
and now with even number
![snr_view_even](https://user-images.githubusercontent.com/17382592/121579065-a5437c80-ca2b-11eb-8f95-4cfe55732255.jpg)

**Comment by DG9BFC** [comment]
higher numbers show less high spikes but it is still going up and down so best would be to only use the even settings?!?

**Comment by JvanKatwijk** [comment]
TII data is ytransmitted in each second frame, so there will be a difference in SNR measurements between first and second frames

**Comment by DG9BFC** [comment]
ok you explained it ... maybe you sould add a hint about setting to even numbers only
