### ISSUE TITLE
Detection of missing device not (more?) working

### ISSUE THREAD

**Issue by tomneda** [JvanKatwijk/qt-dab#290]
Related to this current HEAD commit on master https://github.com/JvanKatwijk/qt-dab/commit/52371b4c08314ecef96aa4a3da65752df40f7073 :

When I remove my RTL-stick on start of QT-DAB I get a quite uninformative message on the command line (not a message box):

```
terminate called after throwing an instance of 'rtlsdr_exception*'
14:15:31: /home/work/Programming/GIT/tomneda/qt-dab-linux/build-qt-dab-s4-Desktop_Qt_5_15_2_GCC_64bit-Debug/qt-dab-4.6 crashed.

```
While debugging the debugger goes correctly in this section:
![grafik](https://github.com/JvanKatwijk/qt-dab/assets/103888527/1572a028-8bc2-4aaa-9930-77bf3300dab6)
(the warning tells already the problem)

When I remove the new here then it works. Looking this: 
![grafik](https://github.com/JvanKatwijk/qt-dab/assets/103888527/50f2e1d0-1056-441c-af3c-46e208f784b0)

Then this message box is shown like it should do, I guess:
![grafik](https://github.com/JvanKatwijk/qt-dab/assets/103888527/694657c8-a83a-40ff-aeff-4662d3a921c0)

**Comment by JvanKatwijk** [comment]
fixed
