### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by davidea72** [JvanKatwijk/qt-dab#316]
hi
i ask you, maybe i'm missing something, or what i'm asking is outside of your scope
i want to install a raspberry at my home and use it remotely sharing it with some friends, then 
is there a way to have all the data about the station and ensamble outside the program , like an api ? to get it with some python script and make available in an http interface? would be great to get the audio stream too!!!

**Comment by andimik** [comment]
Dear @davidea72

You could give https://github.com/AlbrechtL/welle.io a try. It comes with a web interface and you can stream the audio over the internet.

For example 

https://dabmonitor.com/test-1-windows.html

(but currently out of order)

https://ale.cx/ALEX/2021/03/welle-cli-sdr-dab-server-on-raspberry-pi-4/

There you can see a screenshot.

**Comment by davidea72** [comment]
@andimik thanks, this is very close to what i'm searching for!!! i've tried it and it's ok for streaming and for the basic info
