### ISSUE TITLE
desktop file and icon missing for Linux

### ISSUE THREAD

**Issue by probonopd** [JvanKatwijk/qt-dab#32]
[desktop file](https://standards.freedesktop.org/desktop-entry-spec/latest/) and icon are missing for Linux. Please provide some, so that we can get it to show up in the menus.

**Comment by andimik** [comment]
You can create your own desktop file, see http://www.raspberry-projects.com/pi/pi-operating-systems/raspbian/gui/desktop-shortcuts

It should contain these lines:

```
[Desktop Entry]
Name=My Name
Comment=My application which does this
Icon=/usr/share/pixmaps/openbox.xpm
Exec=/usr/bin/leafpad
Type=Application
Encoding=UTF-8
Terminal=false
Categories=None;
```

**Comment by probonopd** [comment]
Yes, but it would be nice if a "make install" would do this automatically. By the way, the `/usr/bin/` and `/usr/share/` can and should be left away.
