### ISSUE TITLE
support for Airspy HF+ ?

### ISSUE THREAD

**Issue by moolight-seashell** [JvanKatwijk/qt-dab#339]
the readme is unclear if qt-dab support all the airspy device or not

**Comment by andimik** [comment]
@moolight-seashell

Although you have closed the issue by yourself, let me just tell youthat only Airspy R2 and Mini are supported.

The bandwidth of HF+ is optimized for analog AM and FM signals. DAB requires a larger bandwidth (around 2 MHz) which the HF+ can't offer.

**Comment by moolight-seashell** [comment]
@andimik 
hey thanksfor your reply, yep ov see this is why i closed my issue
but thanks anyway
