### ISSUE TITLE
Wrong frequency for channel 13A

### ISSUE THREAD

**Issue by eivindsl** [JvanKatwijk/qt-dab#57]
typo in src/various/band-handler.cpp, the frequency for channel 13A shall be 230.784, not 230.748.

**Comment by andimik** [comment]
How did you find that out? Do you live in Norway? 

Anyway, thanks :-) 

In the meanwhile you can certainly build it with the correct frequency.

**Comment by andimik** [comment]
Fixed in Pull request https://github.com/JvanKatwijk/qt-dab/pull/59

**Comment by JvanKatwijk** [comment]
Pulled and solved
