### ISSUE TITLE
temp folder under Windows not valid 

### ISSUE THREAD

**Issue by andimik** [JvanKatwijk/qt-dab#58]
I know it was me giving you the hint how to get the temp folder under Windows (%tmp%). But it seems you should use the following function in C++ to get it. Currently qt-dab does not write slides

> cannot write file %tmp%\qt-pictures\file.png

https://stackoverflow.com/questions/8087805/how-to-get-system-or-user-temp-folder-in-unix-and-windows
https://msdn.microsoft.com/en-us/library/windows/desktop/aa364992(v=vs.85).aspx

**Comment by JvanKatwijk** [comment]
addressed by using Qt functions for getting the tmppath and for establishing that the directory exists
